version: '3'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
